# Generated by Django 4.2.2 on 2023-06-20 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento_Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento_Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(max_length=200)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('fecha_futura', models.DateField(verbose_name='Proxima Revision')),
                ('km', models.IntegerField(default=0)),
                ('vehiculo_id', models.IntegerField(default=0)),
                ('tipo_mantenimiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mantenimiento_tipo')),
            ],
        ),
    ]
