# Generated by Django 4.2.2 on 2023-06-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento_tipo',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
    ]
